# Generated by Django 2.2.3 on 2019-11-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_watching'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watching',
            options={'ordering': ['-date']},
        ),
    ]
