# Generated by Django 2.2.3 on 2019-11-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191120_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', 'Do Not Watch Again'), ('2', 'Did Not Like It'), ('3', 'It Was Kinda Good'), ('4', 'I Liked It'), ('5', 'I Loved This Movie')], default='1'),
        ),
    ]
